TestWebsite/TestWebsite/Models/UserObservation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace TestWebsite.Models
{
    public class UserObservationModel
    {
        [Key]
        public int Obs_Id { get; set; }
        [Required]
        [Display(Name = "Observations Note")]
        public string Obs_Note { get; set; }
        [Required]
        [Display(Name = "Art Navn")]
        public string Art_Navn { get; set; }
        [Required]
        [Display(Name = "Art Beskrivelse")]
        public string Art_Beskrivelse { get; set; }
        [Required]
        [Display(Name = "Art Familie")]
        public string Art_Familie { get; set; }
        [Required]
        [Display(Name = "Art Orden")]
        public string Art_Orden { get; set; }
        [Required]
        [Display(Name = "Art Klasse")]
        public string Art_Klasse { get; set; }
        [Required]
        [Display(Name = "By")]
        public string Bynavn { get; set; }
        [Required]
        [Display(Name = "Lokation")]
        public string Geo_lokation { get; set; }       
    }
}

TestWebsite/TestWebsite/Controllers/UserObservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestWebsite.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using TestWebsite.Helper;
using System.Diagnostics;

namespace TestWebsite.Controllers
{
    public class UserObservationsController : Controller
    {
        [Authorize]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, int? pageSize)
        {           
            FloraFaunaWebsite_db_Entities1 observation_db = new FloraFaunaWebsite_db_Entities1();

            int UserId = User.Identity.GetUserId<int>();

            ViewBag.CurrentSort = sortOrder;

            // Adding search parameters for sorting the list
            ViewBag.DatoSortParm = sortOrder == "dato" ? "dato_desc" : "dato";
            ViewBag.BySortParm = sortOrder == "by" ? "by_desc" : "by";
            ViewBag.LokationSortParm = sortOrder == "lokation" ? "lokation_desc" : "lokation";
            ViewBag.NavnSortParm = sortOrder == "navn" ? "navn_desc" : "navn";
            ViewBag.KlasseSortParm = sortOrder == "klasse" ? "klasse_desc" : "klasse";
            ViewBag.FamilieSortParm = sortOrder == "familie" ? "familie_desc" : "familie";
            ViewBag.OrdenSortParm = sortOrder == "orden" ? "orden_desc" : "orden";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var observations = observation_db.GetObservationsByParams(null, null, null, "", null, 1, null,null);

            // add filtering functionality to the index
            if (!String.IsNullOrEmpty(searchString))
            {
                sortOrder = "search";                
            }

            Debug.WriteLine("sortorder: " + sortOrder);
                                                                                                      
            // sort the observations
            switch (sortOrder)
            {
                case "search":
                    observations = observation_db.GetObservationsByParams(null, null, null, searchString, null, UserId, null,null); 
                    break;
                case "dato":
                    observations = observation_db.GetObservationsByParams(null, null, null,"", null, UserId, null, "Dato");
                    break;             
                case "by":
                    observations = observation_db.GetObservationsByParams(null, null, null,"", null, UserId, null, "By");
                    break;              
                case "lokation":
                    observations = observation_db.GetObservationsByParams(null, null, null,"", null, UserId, null, "Lokation");
                    break;                
                case "navn":
                    observations = observation_db.GetObservationsByParams(null, null, null,"", null, UserId, null, "ArtNavn");
                    break;               
                case "klasse":
                    observations = observation_db.GetObservationsByParams(null, null, null,"", null, UserId, null, "ArtKlasse");
                    break;            
                case "familie":
                    observations = observation_db.GetObservationsByParams(null, null, null,"", null, UserId, null, "ArtFamilie");
                    break;             
                case "orden":
                    observations = observation_db.GetObservationsByParams(null, null, null,"", null, UserId, null, "ArtOrden");
                    break;              
                default:                           
                    observations = observation_db.GetObservationsByParams(null, null, null,"", null, UserId, null, "By");
                    break;
            }

            var new_obs = observations.ToList();
            int ps = (pageSize ?? 10);
            ViewBag.PageSize = PageHelper.CreatePageSizeList(ps);
            ViewBag.CurrentPageSize = ps;
            int pageNumber = (page ?? 1);
            return View(new_obs.ToPagedList(pageNumber, ps));
        }

        public ActionResult AllObservations(string sortOrder, string currentFilter, string searchString, int? page, int? pageSize)
        {
            FloraFaunaWebsite_db_Entities1 observation_db = new FloraFaunaWebsite_db_Entities1();
           
            ViewBag.CurrentSort = sortOrder;

            // Adding search parameters for sorting the list
            ViewBag.DatoSortParm = sortOrder == "dato" ? "dato_desc" : "dato";
            ViewBag.BySortParm = sortOrder == "by" ? "by_desc" : "by";
            ViewBag.LokationSortParm = sortOrder == "lokation" ? "lokation_desc" : "lokation";
            ViewBag.NavnSortParm = sortOrder == "navn" ? "navn_desc" : "navn";
            ViewBag.KlasseSortParm = sortOrder == "klasse" ? "klasse_desc" : "klasse";
            ViewBag.FamilieSortParm = sortOrder == "familie" ? "familie_desc" : "familie";
            ViewBag.OrdenSortParm = sortOrder == "orden" ? "orden_desc" : "orden";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var observations = observation_db.GetObservationsByParams(null, null, null, "", null,null, null, null);

            // add filtering functionality to the index
            if (!String.IsNullOrEmpty(searchString))
            {
                sortOrder = "search";
            }

            Debug.WriteLine("sortorder: " + sortOrder);

            // sort the observations
            switch (sortOrder)
            {
                case "search":
                    observations = observation_db.GetObservationsByParams(null, null, null, searchString, null,null, null, null);
                    break;
                case "dato":
                    observations = observation_db.GetObservationsByParams(null, null, null, "", null,null, null, "Dato");
                    break;
                case "by":
                    observations = observation_db.GetObservationsByParams(null, null, null, "", null,null, null, "By");
                    break;
                case "lokation":
                    observations = observation_db.GetObservationsByParams(null, null, null, "", null,null, null, "Lokation");
                    break;
                case "navn":
                    observations = observation_db.GetObservationsByParams(null, null, null, "", null,null, null, "ArtNavn");
                    break;
                case "klasse":
                    observations = observation_db.GetObservationsByParams(null, null, null, "", null,null, null, "ArtKlasse");
                    break;
                case "familie":
                    observations = observation_db.GetObservationsByParams(null, null, null, "", null,null, null, "ArtFamilie");
                    break;
                case "orden":
                    observations = observation_db.GetObservationsByParams(null, null, null, "", null,null, null, "ArtOrden");
                    break;
                default:
                    observations = observation_db.GetObservationsByParams(null, null, null, "", null,null, null, "By");
                    break;
            }

            var new_obs = observations.ToList();
            int ps = (pageSize ?? 10);
            ViewBag.PageSize = PageHelper.CreatePageSizeList(ps);
            ViewBag.CurrentPageSize = ps;
            int pageNumber = (page ?? 1);
            return View(new_obs.ToPagedList(pageNumber, ps));
        }

    }
}

TestWebsite/TestWebsite/Views/UserObservations/AllObservations.cshtml
@model PagedList.IPagedList<TestWebsite.Models.sp_Observation_By_Search_Params_Result>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Observationer";
}

<br />
@using (Html.BeginForm("AllObservations", "UserObservations", FormMethod.Get))
{
    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
    <br />
    <button type="submit" style="margin:2px; " class="btn btn-primary"><span style="font-size:large;">Search</span></button>
    <button type="button" style="margin:2px; " class="btn btn-info" onclick="location.href=@Url.Action("Create", "UserObservations")"><span style="font-size:large;">Tilføj en observation</span></button>
}
<br />

<table class="table table-striped table-hover table-responsive table-condensed">
    <tr>
        <th>
            <h3 style="font-size:medium">
                <span style="font-weight:bolder">
                    @Html.ActionLink("Dato", "AllObservations", new { sortOrder = ViewBag.DatoSortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                </span>
            </h3>
        </th>
        <th>
            <h3 style="font-size:medium">
                <span style="font-weight:bolder">
                    @Html.ActionLink("By", "AllObservations", new { sortOrder = ViewBag.BySortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                </span>
            </h3>
        </th>
        <th>
            <h3 style="font-size:medium">
                <span style="font-weight:bolder">
                    @Html.ActionLink("Lokation", "AllObservations", new { sortOrder = ViewBag.LokationSortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                </span>
            </h3>
        </th>
        <th>
            <h3 style="font-size:medium">
                <span style="font-weight:bolder">
                    @Html.ActionLink("Navn", "AllObservations", new { sortOrder = ViewBag.NavnSortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                </span>
            </h3>
        </th>
        <th>
            <h3 style="font-size:medium">
                <span style="font-weight:bolder">
                    @Html.ActionLink("Familie", "AllObservations", new { sortOrder = ViewBag.FamilieSortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                </span>
            </h3>
        </th>
        <th>
            <h3 style="font-size:medium">
                <span style="font-weight:bolder">
                    @Html.ActionLink("Orden", "AllObservations", new { sortOrder = ViewBag.OrdenSortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                </span>
            </h3>
        </th>
        <th>
            <h3 style="font-size:medium">
                <span style="font-weight:bolder">
                    @Html.ActionLink("Klasse", "AllObservations", new { sortOrder = ViewBag.KlasseSortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                </span>
            </h3>
        </th>


        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="col-lg-1">
                <span style="font-size: 16px;">@Html.DisplayFor(modelItem => item.ObservationsDag)</span>
            </td>
            <td class="col-lg-2">
                <span style="font-size: 16px;">@Html.DisplayFor(modelItem => item.Bynavn)</span>
            </td>
            @{
        string lokation1 = item.GEO;
        string lokation2 = lokation1.Substring(7);
        int lenght = lokation2.Length;
        string item_string = lokation2.Substring(0, lenght - 1);
        string[] longi_lati = item_string.Split(' ');
        string new_lokation = longi_lati[0].Substring(0, 6) + "," + longi_lati[1].Substring(0, 6);
            }
            <td class="col-lg-2">
                <span style="font-size: 16px;">@Html.DisplayFor(modelItem => new_lokation)</span>
            </td>
            <td class="col-lg-2">
                <span style="font-size: 16px;">@Html.DisplayFor(modelItem => item.Artnavn)</span>
            </td>
            <td class="col-lg-1">
                <span style="font-size: 16px;">@Html.DisplayFor(modelItem => item.Familie)</span>
            </td>
            <td class="col-lg-1">
                <span style="font-size: 16px;">@Html.DisplayFor(modelItem => item.Orden)</span>
            </td>
            <td class="col-lg-1">
                <span style="font-size: 16px;">@Html.DisplayFor(modelItem => item.Klasse)</span>
            </td>
            <td class="col-lg-2">
                <button type="button" class="btn btn-warning col-md-3" onclick="location.href='@Url.Action("Edit", "UserObservations", new { id = item.Observations_id })';return false;"><span class="glyphicon glyphicon-pencil"></span></button>
                <button type="button" class="btn btn-info col-md-3 col-md-offset-1" onclick="location.href='@Url.Action("Delete", "UserObservations", new { id = item.Observations_id })' ;return false;"><span class="glyphicon glyphicon-trash"></span></button>
            </td>
        </tr>
    }

</table>

@using (Html.BeginForm("AllObservations", "UserObservations", FormMethod.Get))
{
    <p>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of
        /@Model.PageCount - Rows pr page: @Html.DropDownList("PageSize", @ViewBag.PageSize as SelectList, new { id = "changePageSize" })
    </p>
}

@Html.PagedListPager(Model, page => Url.Action("AllObservations",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize }))

@section scripts
{
    <script type="text/javascript">
        $(function () {
            $('#changePageSize').on('change', function () {

                var pageSize = $(this).val();
                //alert('Pagesize changed to '+pageSize);
                var sortOrder = '@ViewBag.CurrentSort';
                var currentFilter = '@ViewBag.CurrentFilter';
                window.location = "AllObservations?"
                    + "sortOrder=" + sortOrder
                    + "&pageSize=" + pageSize
                    + "&currentFilter=" + currentFilter;
            });
        })

    </script>
}

TestWebsite/TestWebsite/Views/UserObservations/Create.cshtml
@model TestWebsite.Models.sp_Observation_By_User_Id_Result

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>sp_Observation_By_User_Id_Result</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Observationsnote, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Observationsnote, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Observationsnote, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Artnavn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Artnavn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Artnavn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Art_beskrivelse, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Art_beskrivelse, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Art_beskrivelse, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Familie, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Familie, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Familie, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Orden, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Orden, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Orden, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Klasse, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Klasse, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Klasse, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Bynavn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Bynavn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Bynavn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Geo_Lokation, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Geo_Lokation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Geo_Lokation, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

TestWebsite/TestWebsite/Views/UserObservations/Delete.cshtml
@model TestWebsite.Models.sp_Observation_By_User_Id_Result

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>sp_Observation_By_User_Id_Result</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Observationsnote)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Observationsnote)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Artnavn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Artnavn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Art_beskrivelse)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Art_beskrivelse)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Familie)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Familie)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Orden)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Orden)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Klasse)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Klasse)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Bynavn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Bynavn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Geo_Lokation)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Geo_Lokation)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

TestWebsite/TestWebsite/Views/UserObservations/Details.cshtml
@model TestWebsite.Models.sp_Observation_By_User_Id_Result

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>sp_Observation_By_User_Id_Result</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Observationsnote)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Observationsnote)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Artnavn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Artnavn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Art_beskrivelse)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Art_beskrivelse)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Familie)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Familie)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Orden)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Orden)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Klasse)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Klasse)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Bynavn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Bynavn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Geo_Lokation)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Geo_Lokation)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Observations_id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

TestWebsite/TestWebsite/Views/UserObservations/Index.cshtml
@model PagedList.IPagedList<TestWebsite.Models.sp_Observation_By_Search_Params_Result>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Observationer";    
}

<br />
@using (Html.BeginForm("Index", "UserObservations", FormMethod.Get))
{
    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
    <br />
    <button type="submit" style="margin:2px; " class="btn btn-primary"><span style="font-size:large;">Search</span></button>
    <button type="button" style="margin:2px; " class="btn btn-info" onclick="location.href=@Url.Action("Create", "UserObservations")"><span style="font-size:large;">Tilføj en observation</span></button>
}
<br />

    <table class="table table-striped table-hover table-responsive table-condensed">
        <tr>
            <th>
                <h3 style="font-size:medium">
                    <span style="font-weight:bolder">
                        @Html.ActionLink("Dato", "Index", new { sortOrder = ViewBag.DatoSortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                    </span>
                </h3>
            </th>
            <th>
                <h3 style="font-size:medium">
                    <span style="font-weight:bolder">
                        @Html.ActionLink("By", "Index", new { sortOrder = ViewBag.BySortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                    </span>
                </h3>
            </th>
            <th>
                <h3 style="font-size:medium">
                    <span style="font-weight:bolder">
                        @Html.ActionLink("Lokation", "Index", new { sortOrder = ViewBag.LokationSortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                    </span>
                </h3>
            </th>
            <th>
                <h3 style="font-size:medium">
                    <span style="font-weight:bolder">
                        @Html.ActionLink("Navn", "Index", new { sortOrder = ViewBag.NavnSortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                    </span>
                </h3>
            </th>                        
            <th>
                <h3 style="font-size:medium">
                    <span style="font-weight:bolder">
                        @Html.ActionLink("Familie", "Index", new { sortOrder = ViewBag.FamilieSortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                    </span>
                </h3>
            </th>
            <th>
                <h3 style="font-size:medium">
                    <span style="font-weight:bolder">
                        @Html.ActionLink("Orden", "Index", new { sortOrder = ViewBag.OrdenSortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                    </span>
                </h3>
            </th>
            <th>
                <h3 style="font-size:medium">
                    <span style="font-weight:bolder">
                        @Html.ActionLink("Klasse", "Index", new { sortOrder = ViewBag.KlasseSortParm, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize })
                    </span>
                </h3>
            </th>


            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td class="col-lg-1">
                    <span style="font-size: 16px;">@Html.DisplayFor(modelItem => item.ObservationsDag)</span>
                </td>
                <td class="col-lg-2">
                    <span style="font-size: 16px;">@Html.DisplayFor(modelItem => item.Bynavn)</span>
                </td>
                @{
                    string lokation1 = item.GEO;
                    string lokation2 = lokation1.Substring(7);
                    int lenght = lokation2.Length;
                    string item_string = lokation2.Substring(0, lenght - 1);
                    string[] longi_lati = item_string.Split(' ');
                    string new_lokation = longi_lati[0].Substring(0,6)+"," + longi_lati[1].Substring(0,6);                   
                }
                <td class="col-lg-2">
                    <span style="font-size: 16px;">@Html.DisplayFor(modelItem => new_lokation)</span>
                </td>
                <td class="col-lg-2">
                    <span style="font-size: 16px;">@Html.DisplayFor(modelItem => item.Artnavn)</span>
                </td>
                <td class="col-lg-1">
                    <span style="font-size: 16px;">@Html.DisplayFor(modelItem => item.Familie)</span>
                </td>
                <td class="col-lg-1">
                    <span style="font-size: 16px;">@Html.DisplayFor(modelItem => item.Orden)</span>
                </td>
                <td class="col-lg-1">
                    <span style="font-size: 16px;">@Html.DisplayFor(modelItem => item.Klasse)</span>
                </td>
                <td class="col-lg-2">
                    <button type="button" class="btn btn-warning col-md-3" onclick="location.href='@Url.Action("Edit", "UserObservations", new { id = item.Observations_id })';return false;"><span class="glyphicon glyphicon-pencil"></span></button>
                    <button type="button" class="btn btn-info col-md-3 col-md-offset-1" onclick="location.href='@Url.Action("Delete", "UserObservations", new { id = item.Observations_id })' ;return false;"><span class="glyphicon glyphicon-trash"></span></button>
                </td>
            </tr>
        }

    </table>

@using (Html.BeginForm("Index", "UserObservations", FormMethod.Get))
{
    <p>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of
        /@Model.PageCount - Rows pr page: @Html.DropDownList("PageSize", @ViewBag.PageSize as SelectList, new { id = "changePageSize" })
    </p>
}

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, pageSize = ViewBag.CurrentPageSize }))

@section scripts
{
    <script type="text/javascript">
        $(function () {
            $('#changePageSize').on('change', function () {

                var pageSize = $(this).val();
                //alert('Pagesize changed to '+pageSize);
                var sortOrder = '@ViewBag.CurrentSort';
                var currentFilter = '@ViewBag.CurrentFilter';
                window.location = "Index?"
                    + "sortOrder=" + sortOrder
                    + "&pageSize=" + pageSize
                    + "&currentFilter=" + currentFilter;
            });
        })

    </script>
}